accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views


from .views import (
	#Navegación
	display_home,
	display_login,
	logout_user,

	#Procesos de cuenta
	activation_view,
	restore_password_view,
	restore_password_key_view,

	#Administración de cuentas del sistema
	accounts_view,

	#account_update_view,
	LogIn,
	CreateAccount,
	UpdateAccount,
	DeleteAccount,
)


app_name = 'accounts'

urlpatterns = [
	path('home/', display_home, name="home"),
	path('login/', display_login, name="login"),
	path('logout/', logout_user, name="logout"),
    path('logmodal/', LogIn.as_view(), name="logmodal"),
	path('accounts/activate/<activation_key_provided>', activation_view, name="activation"),
	path('reset-link/<password_key_provided>', restore_password_key_view, name="passwordkey"),
	path('restore-password/', restore_password_view, name="restore"),

	path('accounts/', accounts_view, name="accounts"),
	path('accounts/register/', CreateAccount.as_view(), name="register"),
	path('accounts/update/<pk>', UpdateAccount.as_view(), name="update"),
	path('accounts/delete/<pk>', DeleteAccount.as_view(), name='delete'),
]

proyectoweb/urls.py
from django.contrib import admin
from django.urls import path, include
from Activities.views import MostrarActividades
from Activities.views import crearActividad
from Activities.views import editarActividad
from Activities.views import eliminarActividad
from Activities.views import realizarActividad
from Report.views import Pdf
from ReportAdmin.views import Report
from ReportAdmin.views import MostrarActividadesAdmin



urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('FeedActividades/<str:campo>', MostrarActividades, name = "FeedActividades"),
    path ('crear_Actividad/', crearActividad, name = "crear_Actividad"),
    path ('editar_Actividad/<int:id>', editarActividad, name = "editar_Actividad"),
    path ('eliminar_Actividad/<int:id>', eliminarActividad, name = "eliminar_Actividad"),
    path ('actividadEstado/<int:id>', realizarActividad, name = "actividadEstado"),
    path('render/pdf/', Pdf.as_view(),name = "render/pdf"),
    path('render/pdfAdmin/', Report.as_view(),name = "render/pdfAdmin"),
    path('FeedActividadesAdmin/<str:campo>', MostrarActividadesAdmin, name = "FeedActividadesAdmin"),
]
handler404 = 'accounts.views.error_404_view'

accounts/models.py
from django.db import models
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractUser


class Account(AbstractUser):
    pass

class PasswordReset(models.Model):
    user                      = models.OneToOneField(Account, on_delete=models.CASCADE)
    reset_key                 = models.CharField(max_length=200)

    def __unicode__(self):
        return str(self.user)

    def send_password_reset_email(self):
        reset_password_url = "http://localhost:8005/reset-link/" + self.reset_key 
        print("LLave de activación en el modelo: " + self.reset_key)
        context = {
            "reset_password_url": reset_password_url,
            "user": self.user.username,
        }
        message = render_to_string("accounts/reset_password_message.txt", context)
        subject = "Haz solicitado un cambio de contraseña, " + self.user.username +"."
        self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
 
    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.user.email], kwargs)

class EmailConfirmed(models.Model):
    user                      = models.OneToOneField(Account, on_delete=models.CASCADE)
    activation_key            = models.CharField(max_length=200)
    confirmed                 = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.confirmed)

    def send_activation_email(self):
        activation_url = "http://localhost:8005/accounts/activate/" + self.activation_key 
        context = {
            "activation_url": activation_url,
            "user": self.user.username,
        }
        message = render_to_string("accounts/activation_message.txt", context)
        subject = "Activa tu correo, por favor. " + self.user.username +"."
        self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
 
    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.user.email], kwargs)

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, AuthenticationForm
from accounts.models import EmailConfirmed, Account
from django import forms
from django.forms import ModelForm
from bootstrap_modal_forms.forms import BSModalForm, BSModalModelForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin

class AccountCreationForm(PopRequestMixin, CreateUpdateAjaxMixin,
                             UserCreationForm):
    class Meta:
        model = Account
        fields = ['username', 'password1', 'password2', 'first_name', 'email']

class AuthenticationForm(AuthenticationForm):
    class Meta:
        model = Account 
        fields = ['username', 'password']

class AccountForm(BSModalModelForm):
	class Meta:
		model = Account
		exclude = ['last_login', 'date_joined', 'is_superuser',
		 'groups', 'user_permissions', 'is_staff']

class AccountUpdateForm(BSModalModelForm):
	class Meta:
		model = Account
		exclude = ['last_login', 'date_joined', 'is_superuser',
		 'groups', 'user_permissions', 'is_staff', 'is_active', 'password']

class SetCustomPasswordForm(SetPasswordForm):
	error_messages = {
        'password_mismatch': "Las contraseñas no son iguales",
    }

	def __init__(self, *args, **kwargs):
		super(SetCustomPasswordForm, self).__init__(*args, **kwargs)
		self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form-control',
		 'placeholder': 'Contraseña', 'required':'True'})
		self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form-control',
		 'placeholder': 'Repite la contraseña', 'required':'True'})

class CreateUserForm(UserCreationForm):
	error_messages = {
        'password_mismatch': "Las contraseñas no son iguales",
    }
	
	class Meta:
		model = Account
		fields = ['username', 'email', 'password1', 'password2']

		widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Usuario', 'required':'True'}),
            'email': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Correo','required':'True'}),
    	}

		error_messages = {
            'username': {
				"unique": "El usuario ya existe",
                'required': "El usuario es obligatorio",
                'invalid': "El usuario es inválido",
				},
			'email': {
				"unique": "El correo ya existe",
                'required': "El correo es obligatorio",
                'invalid': "El correo es inválido",
				},
		}

	def __init__(self, *args, **kwargs):
		super(CreateUserForm, self).__init__(*args, **kwargs)
		self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control',
		 'placeholder': 'Contraseña', 'required':'True'})
		self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control',
		 'placeholder': 'Repite la contraseña', 'required':'True'})

		

accounts/views.py
import re
import random 
import hashlib
import json

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import SetPasswordForm
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import Http404
from django.contrib.auth import get_user_model
from django.views.generic.edit import UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from bootstrap_modal_forms.generic import BSModalLoginView 
from bootstrap_modal_forms.generic import BSModalUpdateView
from bootstrap_modal_forms.generic import  BSModalCreateView
from bootstrap_modal_forms.generic import BSModalDeleteView
from accounts.models import EmailConfirmed, PasswordReset


from .models import Account 
from .forms import AccountForm, AccountUpdateForm, SetCustomPasswordForm, CreateUserForm, AuthenticationForm, AccountCreationForm

User = get_user_model()

def display_home(request):
    context = {}
    return render(request, 'accounts/home.html', context)

def display_register(request):
    if request.user.is_superuser: 
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Cuenta creada para ' + user + ", confirma tu correo para poder iniciar sesión")
                return redirect('/login')
    context = {'form':form}
    return render(request, 'accounts/register.html', context)

def display_login(request):
    context = {}
    return render(request, 'accounts/login.html', context)

SHA1_RE = re.compile('^[a-f0-9]{40}$')

def activation_view(request, activation_key_provided):
    if SHA1_RE.search(activation_key_provided):
        try:
            user_confirmed =  EmailConfirmed.objects.get(activation_key = activation_key_provided)
        except EmailConfirmed.DoesNotExist:
            user_confirmed = None
            raise Http404
        if user_confirmed is not None and not user_confirmed.confirmed:
            message = "El correo ha sido confirmado correctamente."
            user_confirmed.confirmed = True
            user_confirmed.save()
        elif user_confirmed is not None and user_confirmed.confirmed:
            message = "El correo ya ha sido confirmado."
        else:
            message = ""

        context = {"message": message}
        return render(request, 'accounts/activation_complete.html', context)
    else: 
        raise Http404

def restore_password_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        try:
            user =  User.objects.get(username = username)
        except User.DoesNotExist:
            user = None
            message = "El usuario no existe, verifica que es correcto"
            messages.info(request, message)
        if user is not None:
            password_already_forgotten, password_reset_created = PasswordReset.objects.get_or_create(user=user)
            if password_reset_created:
                short_hash = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:5]
                reset_key = hashlib.sha1((short_hash+username).encode('utf-8')).hexdigest()
                password_already_forgotten.reset_key = reset_key
                password_already_forgotten.save()
                password_already_forgotten.send_password_reset_email()
                message = "Se ha mandado un mensaje al correo "
                messages.info(request, message)
            else:
                message = "No se ha podido enviar el correo "
                messages.info(request, message)
    context = {}
    return render(request, 'accounts/password_reset.html', context)

def restore_password_key_view(request, password_key_provided):
    if SHA1_RE.search(password_key_provided):
        message = ''
        try:
            password_change =  PasswordReset.objects.get(reset_key = password_key_provided)
            user = password_change.user
            account = None
            account = User.objects.get(username=user.username)
        except PasswordReset.DoesNotExist:
            password_change = None
            raise Http404
        if password_change is not None:
            form = SetCustomPasswordForm(request.user, request.POST)
            if request.method == 'POST':
                if form.is_valid():
                    password = form.cleaned_data.get('new_password1')
                    account.set_password(password)
                    if account is not None: 
                        account.save()
                        password_change.reset_key = ""
                        password_change.save()
                        messages.success(request, 'La contraseña ha sido cambiada satisfactoriamente.')
                        return redirect('/login')
                else:
                    message ='La contraseña no se ha podido cambiar'
        else:
            message = 'El link es inválido, por favor envía un nuevo formulario para cambiar su contraseña'
    else: 
        raise Http404
    context = {'form':form, "message": message}
    return render(request, 'accounts/password_forgotten.html', context)

def error_404_view(request, exception):
    return render(request, 'accounts/404.html')

@login_required
def accounts_view(request):
    accounts = User.objects.all()
    context = {'accounts':accounts}
    return render(request, 'accounts/accounts_crud.html', context)

class LogIn(BSModalLoginView):
    authentication_form = AuthenticationForm
    template_name = 'accounts/modals/login_modal.html'
    success_message = 'Se inicio sesión satisfactoriamente.'
    extra_context = dict(success_url=reverse_lazy('accounts:home'))

class CreateAccount(BSModalCreateView):
    form_class = AccountCreationForm
    success_message = 'Se ha creado un usuario con éxito'
    template_name = 'accounts/modals/create_modal.html'
    success_url = reverse_lazy('accounts:accounts')
 
class UpdateAccount(BSModalUpdateView):
    model = User
    form_class = AccountUpdateForm
    success_message = 'Se ha actualizado con éxito'
    template_name = 'accounts/modals/update_modal.html'
    success_url = reverse_lazy('accounts:accounts')

class DeleteAccount(BSModalDeleteView):
    model = User
    success_message = 'Se ha eliminado con éxito'
    template_name = 'accounts/modals/delete_modal.html'
    success_url = reverse_lazy('accounts:accounts')

def logout_user(request):
    logout(request)
    return redirect('/login')

accounts/templates/accounts/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

accounts/templates/accounts/accounts_crud.html
{% extends 'accounts/base.html' %}
{% load static %} 
{% block title%}
Administración de usuarios
{% endblock %} 
{% block style_base %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'accounts/accounts_crud.css' %}"
/>
{% endblock %} {% block real_content %} {% include "accounts/_modal.html" %}

<div class="table-cont">
  <div class="table-title">
    <nav class="nav nav-pills nav-fill">
      <h2>Administración de <b>usuarios</b></h2>
      <button type="button" class="add-account btn btn-sm btn-success">
        Agregar
      </button>
    </nav>
  </div>
  <table class="table table-bordered table-dark table-hover">
    {% for account in accounts %} {% if forloop.first %}
    <thead class="thead-dark">
      <tr>
        <th scope="col">
          <input
            type="checkbox"
            id="checkbox"
            name="get-all"
            value="check-all"
          />
        </th>
        <th scope="col">Estado</th>
        <th scope="col">Usuario</th>
        <th scope="col">Nombre</th>
        <th scope="col">Correo</th>
        <th scope="col">Rol</th>
        <th scope="col">Acciones disponibles</th>
      </tr>
    </thead>
    {% endif %}
    <div class="table-row">
      <tr>
        <td>
          <input
            type="checkbox"
            id="checkbox"
            name="{{ account.username }}"
            value="check"
          />
        </td>
          {% if account.is_active == False %}
        <td class="bg-warning">Cuenta sin activar</td>
        {% else %}
        <td class="bg-success">Cuenta activada</td>
        {% endif %}
        <td>{{ account.username }}</td>
        <td>{{ account.first_name}}</td>
        <td>{{ account.email }}</td>
        {% if account.is_superuser == False %}
        <td>Invitado</td>
        {% else %}
        <td>Administrador</td>
        {% endif %}
        <td>
          <button
            type="button"
            class="update-account btn btn-sm btn-warning"
            data-id="{% url 'accounts:update' account.pk %}"
          >
            <span class="fa fa-pencil"></span>
          </button>

          <button
            type="button"
            class="delete-account btn btn-sm btn-danger"
            data-id="{% url 'accounts:delete' account.pk %}"
          >
            <span class="fa fa-trash"></span>
          </button>

          <script type="text/javascript">
            $(function () {
              //Agrega una nueva cuenta
              $(".add-account").modalForm({
                formURL: "{% url 'accounts:register' %}",
              });

              //Actualiza la cuenta seleccionada
              $(".update-account").each(function () {
                $(this).modalForm({
                  formURL: $(this).data("id"),
                });
              });

              //Elimina la cuenta seleccionada
              $(".delete-account").each(function () {
                $(this).modalForm({
                  formURL: $(this).data("id"),
                });
              });
            });
          </script>
        </td>
      </tr>
    </div>
    {% endfor %}
  </table>
</div>

{% endblock %}

accounts/templates/accounts/activation_complete.html
{% extends 'accounts/base.html' %}

{% block real_content %}
    <h1>{{message}}</h1>
{% endblock %}

accounts/templates/accounts/base.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/password_reset.css' %}">

    
    
    <title>{% block title %}{% endblock %}</title>
        {% block style_base %}
        {% endblock %}  
</head>

<body>
    {% block content %}

    {% block navigation %}

    {% if user.is_authenticated %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'accounts:home' %}">Gestión de Actividades de Centro de Investigación e Innovación en Educación
                Superior</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:accounts' %}">Cuentas de invitado</a>
                        
                    </li>
                     <li class="nav-item">
                        
                        <a class="nav-link" href="{% url 'FeedActividadesAdmin' campo="account" %}">Actividades</a>
                    </li>
                    {% else %}
                        <a class="nav-link" href="{% url 'FeedActividades' campo="nombre" %}">Actividades</a>
                    {% endif %}
                    
                   
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Cerrar sesión</a>
                    </li>
                </ul>
            </div>
        </nav>

    </header>

    {% endif %}

    {% endblock %}

    {% block real_content %}

    {% block scripts %}
    {% endblock scripts %}
    
    {% endblock %}


    {% endblock %}

</body>


</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% block real_content %}
<h1>Página principal</h1>
{% if user.is_superuser %}
<h2>Bienvenido a tu cuenta  Administrador</h2>
<a class="btn btn-primary" href="{% url 'FeedActividadesAdmin' campo="nombre" %}">Actividades</a>
{% else %}
<h2>Bienvenido a tu cuenta Invitado</h2>
<h4>Este sistema es para la administración de tus tareas, para comenzar a administrar tus tareas da click en el botón "Actividades"</h4>
<div align = center>
<a class="btn btn-primary" href="{% url 'FeedActividades' campo="nombre" %}">Actividades</a>
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block real_content %}

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<div>
</div>
<div class="card" style="width: 500px; height: 400px;">
    <div class="card-header">
        Bienvenido!
    </div>
    <div align=center>
    
    <img src="https://www.logaster.com/blog/wp-content/uploads/2018/05/LogoMakr.png"/>
    <button id="login-btn" class="btn btn-dark .btn-sm" id="buton-ingresa">Ingresar</button>
    </div>
    

    <div class="password-container">
        <a href="{% url 'accounts:restore' %}">No recuerdo mi contraseña</a>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#login-btn").modalForm({
            formURL: "{% url 'accounts:logmodal' %}"
        });
    });
</script>
</div>
{% endblock %}

accounts/templates/accounts/password_forgotten.html
{% extends 'accounts/base.html' %}

{% block real_content %}
  <div class="card" style="width: 500px; height: 450px;">
    <div class="card-header">
      Recuperación de contraseña
    </div>
    <form method="post">
      {% csrf_token %}
      {{form.new_password1}}
      {{form.new_password2}}
      <button type="submit" class="btn btn-dark .btn-sm" 
      id="buton-cambia">Cambiar contraseña</button>
    </form>
    <p>{{message}}</p>
    {% for field in form %}
    <p id="errors">{{field.errors}}</p>
    {% endfor %}
  </div>
  </div>
  {% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}

{% block real_content %}

   
    <div class="card" style="width: 500px; height: 400px;">
        <div class="card-body">
            <div class="card-header">
                Recuperación de contraseña
            </div>
            <p class="card-text">
                <label class="user-notification">
                    Ingresa el usuario para el sistema de gestión de actividades
                    que te asignaron al registrarte.
                    Te enviaremos un enlace al correo ligado a tu cuenta para
                    restablecer tu contraseña.
                </label>
            </p>
            <form method="POST">
                {% csrf_token %}
                <div class="input-container">
                    <input type="text" placeholder="Usuario" name="username" required>
                </div>
                <div class="submit-container">
                    <button type="submit" class="btn btn-dark .btn-sm" id="buton-ingresa">Recuperar</button>
                </div>
                {% for message in messages %}
					<p id="messages">{{message}}</p>
                {% endfor %}	
            </form>
        </div>
    </div>

{% endblock %}